#!/bin/bash

SUMMARY='
Convert video files to MP4 format.
'
AUTHOR='Clint McGraw <clint@clintosaurous.com>'
VERSION='2.0.0'
LAST_UPDATED='2022-09-29'


. /opt/clintosaurous/core/lib/sh/general.sh


if [ -z "$1" ]; then
    echo "Usage: `basename '"$1"'` /video/file {/video/file ...}" >&2
    exit 1
fi


while [ -n "$1" ]
do
    SRC=$1
    shift
    if [ -n "`echo '$SRC' | egrep '\.mp4\$'`" ]; then
        MP4FILE="$SRC.mp4"
    else
        MP4FILE=`echo "$SRC" | sed -E 's/\.\w+$/.mp4/'`
    fi
    echo
    echo "Converting $SRC -> $MP4FILE ..."
    echo
    ffmpeg -i "$SRC" -c:v libx264 -tune film -preset slow -ac 2 -ab 256K \
        "$MP4FILE"
done

echo
echo "Run time: `run_time`"
