#!/opt/clintosaurous/venv/bin/python3 -Bu

"""
Queries the LibreNMS database for host uptime information for each host and
outputs to a text table.
"""


import clintosaurous.credentials as credentials
import clintosaurous.datetime
import clintosaurous.db
import clintosaurous.text


VERSION = '3.1.0'
LAST_UPDATE = '2022-10-15'


if __name__ == '__main__':
    user, passwd = credentials.data().get('mysql-report_ro')
    db = clintosaurous.db.connect(
        host='mysql1.clintosaurous.com',
        user=user,
        passwd=passwd,
        database='librenms',
        logging=False
    )
    sql = """
        select
            case
                when display is null then hostname
                else display
            end as hostname,
            uptime
        from devices
        where uptime is not null
        order by hostname
    """
    cursor = db.cursor()
    cursor.execute(sql)

    rpt_rows = [["Host", "Uptime"]]
    for db_row in cursor:
        row = list(db_row)
        row[1] = clintosaurous.datetime.run_time(row[1])
        rpt_rows.append(row)
    cursor.close()

    print(clintosaurous.text.table(rpt_rows))
